# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Applications', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
        migrations.AddField(
            model_name='windowsapp',
            name='appName',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
